# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18bda6c525ac4d769aaf689522a9415d43fa9ece13661e4b6dc30b309f131ec6be9007fcd137171589c7d9d746f7804cf23818a382bd5d32524ef3aa1810935b

test:
  secret_key_base: 341c155d4070f6e96fde7cbf099fac240961f250ef763d6e7c10e519c36e99f90a656153477731ca180dae04659127370bcfda671e954f577526d66fda2c8cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
